// base mini-config for search icon and vector engines

export const iconAndVectorEngines: Object = {
  flaticon: {
    id: "card-flaticon",
    name: "Flaticon",
    key: "flaticon",
    url: "https://www.flaticon.com/",
    urls: [{ type: "icon", link: "https://www.flaticon.com/search?word=" }],
    located: "Spain",
    svgName: "#flaticon-svg",
    keyColor: "#69E781",
    logoSize: [100, 70],
    typeEngine: "icons and vectors",
  },
  icons8: {
    id: "card-icons8",
    name: "Icons8",
    key: "icons8",
    url: "https://www.icons8.com/",
    urls: [{ type: "icon", link: "https://icons8.com/icons/set/" }],
    located: "USA",
    svgName: "#icons8-svg",
    keyColor: "#1FB141",
    logoSize: [70, 70],
    typeEngine: "icons and vectors",
  },
  freevector: {
    id: "card-freevector",
    name: "Freevector",
    key: "freevector",
    url: "https://www.freevector.com/",
    urls: [{ type: "vector", link: "https://www.freevector.com/vector/" }],
    located: "Various",
    svgName: "#freevector-svg",
    keyColor: "#FFFFFF",
    logoSize: [70, 70],
    typeEngine: "icons and vectors",
  },
  fontawesome: {
    id: "card-fontawesome",
    name: "Font Awesome",
    key: "fontawesome",
    url: "https://fontawesome.com/",
    urls: [{ type: "icon", link: "https://fontawesome.com/search?q=" }],
    located: "USA",
    svgName: "#fontawesome-svg",
    keyColor: "#339AF0",
    logoSize: [70, 70],
    typeEngine: "icons and vectors",
  },
  freepik: {
    id: "card-freepik",
    name: "Freepik",
    key: "freepik",
    url: "https://www.freepik.com/",
    urls: [
      {
        type: "icon",
        link: "https://www.freepik.com/search?&type=icon&query=",
      },
      {
        type: "vector",
        link: "https://www.freepik.com/search?&type=vector&query=",
      },
    ],
    located: "Spain",
    svgName: "#freepik-svg",
    keyColor: "#1E61C6",
    logoSize: [70, 70],
    typeEngine: "icons and vectors",
  },
  addthenounproject: {
    id: "card-addthenounproject",
    name: "Noun Project",
    key: "addthenounproject",
    url: "https://thenounproject.com/",
    urls: [
      { type: "icon", link: "https://thenounproject.com/search/icons/?q=" },
    ],
    located: "USA",
    svgName: "#thenounproject-svg",
    keyColor: "#FFFFFF",
    logoSize: [100, 70],
    typeEngine: "icons and vectors",
  },
  addvecteezy: {
    id: "card-addvecteezy",
    name: "Vecteezy",
    key: "addvecteezy",
    url: "https://www.vecteezy.com/",
    urls: [{ type: "vector", link: "https://www.vecteezy.com/free-vector/" }],
    located: "USA",
    svgName: "#vecteezy-svg",
    keyColor: "#FF7802",
    logoSize: [70, 70],
    typeEngine: "icons and vectors",
  },
};
