// base mini-config for search text engines

export const textEngines: Object = {
  google: {
    id: "card-google",
    name: "Google",
    key: "google",
    urlToSite: "https://www.google.com/",
    urls: [{ type: "text", link: "https://www.google.com/search?q=" }],
    located: "USA",
    svgName: "#google-svg",
    keyColor: "#4285F4",
    logoSize: [70, 70],
    typeEngine: "text",
  },
  duckduckgo: {
    id: "card-duckduckgo",
    name: "DuckDuckGo",
    key: "duckduckgo",
    urlToSite: "https://duckduckgo.com/",
    urls: [{ type: "text", link: "https://duckduckgo.com/?q=" }],
    located: "USA",
    svgName: "#duckduckgo-svg",
    keyColor: "#DE5833",
    logoSize: [70, 70],
    typeEngine: "text",
  },
  bing: {
    id: "card-bing",
    name: "Bing",
    key: "bing",
    urlToSite: "https://www.bing.com/",
    urls: [{ type: "text", link: "https://www.bing.com/search?q=" }],
    located: "USA",
    svgName: "#bing-svg",
    keyColor: "#35D5E1",
    logoSize: [70, 70],
    typeEngine: "text",
  },
  naver: {
    id: "card-naver",
    name: "Naver",
    key: "naver",
    urlToSite: "https://www.naver.com/",
    urls: [
      { type: "text", link: "https://search.naver.com/search.naver?&query=" },
    ],
    located: "South Korea",
    svgName: "#naver-svg",
    keyColor: "#00C73C",
    logoSize: [70, 70],
    typeEngine: "text",
  },
  yahoo: {
    id: "card-yahoo",
    name: "Yahoo",
    key: "yahoo",
    urlToSite: "https://www.yahoo.com/",
    urls: [{ type: "text", link: "https://search.yahoo.com/search?p=" }],
    located: "USA",
    svgName: "#yahoo-svg",
    keyColor: "#720E9E",
    logoSize: [70, 70],
    typeEngine: "text",
  },
  yahooJapan: {
    id: "card-yahooJapan",
    name: "Yahoo JAPAN",
    key: "yahooJapan",
    urlToSite: "https://search.yahoo.co.jp/",
    urls: [{ type: "text", link: "https://search.yahoo.co.jp/search?p=" }],
    located: "Japan",
    svgName: "#yahooJapan-svg",
    keyColor: "#FF0033",
    logoSize: [70, 70],
    typeEngine: "text",
  },
  baidu: {
    id: "card-baidu",
    name: "Baidu",
    key: "baidu",
    urlToSite: "https://www.baidu.com/",
    urls: [{ type: "text", link: "https://www.baidu.com/s?&wd=" }],
    located: "China",
    svgName: "#baidu-svg",
    keyColor: "#2830E1",
    logoSize: [70, 70],
    typeEngine: "text",
  },
  ask: {
    id: "card-ask",
    name: "Ask",
    key: "ask",
    urlToSite: "https://www.ask.com/",
    urls: [{ type: "text", link: "https://www.ask.com/web?q=" }],
    located: "USA",
    svgName: "#ask-svg",
    keyColor: "#CE2027",
    logoSize: [100, 70],
    typeEngine: "text",
  },
  yandex: {
    id: "card-yandex",
    name: "Yandex",
    key: "yandex",
    urlToSite: "https://yandex.com/",
    urls: [{ type: "text", link: "https://yandex.com/search/?text=" }],
    located: "Russia",
    svgName: "#yandex-svg",
    keyColor: "#FC3F1D",
    logoSize: [100, 70],
    typeEngine: "text",
  },
  aol: {
    id: "card-aol",
    name: "Aol",
    key: "aol",
    urlToSite: "https://search.aol.com/",
    urls: [{ type: "text", link: "https://search.aol.com/aol/search?q=" }],
    located: "USA",
    svgName: "#aol-svg",
    keyColor: "#FFF22D",
    logoSize: [70, 70],
    typeEngine: "text",
  },
  ecosia: {
    id: "card-ecosia",
    name: "Ecosia",
    key: "ecosia",
    urlToSite: "https://www.ecosia.org/",
    urls: [{ type: "text", link: "https://www.ecosia.org/search?q=" }],
    located: "Germany",
    svgName: "#ecosia-svg",
    keyColor: "#36ACB8",
    logoSize: [100, 70],
    typeEngine: "text",
  },
  qwant: {
    id: "card-qwant",
    name: "Qwant",
    key: "qwant",
    urlToSite: "https://www.qwant.com/",
    urls: [{ type: "text", link: "https://www.qwant.com/?q=" }],
    located: "France",
    svgName: "#qwant-svg",
    keyColor: "#FFDE00",
    logoSize: [100, 70],
    typeEngine: "text",
  },
  startpage: {
    id: "card-startpage",
    name: "Startpage",
    key: "startpage",
    urlToSite: "https://www.startpage.com/",
    urls: [{ type: "text", link: "https://www.startpage.com/search?query=" }],
    located: "Netherlands",
    svgName: "#startpage-svg",
    keyColor: "#374677",
    logoSize: [100, 70],
    typeEngine: "text",
  },
  dogpile: {
    id: "card-dogpile",
    name: "Dogpile",
    key: "dogpile",
    urlToSite: "https://www.dogpile.com/",
    urls: [{ type: "text", link: "https://www.dogpile.com/search/web?q=" }],
    located: "USA",
    svgName: "#dogpile-svg",
    keyColor: "#7FD3F2",
    logoSize: [100, 70],
    typeEngine: "text",
  },
  exalead: {
    id: "card-exalead",
    name: "Exalead",
    key: "exalead",
    urlToSite: "https://www.exalead.com/",
    urls: [
      { type: "text", link: "https://www.exalead.com/search/web/results/?q=" },
    ],
    located: "France",
    svgName: "#exalead-svg",
    keyColor: "#FFFFFF",
    logoSize: [70, 70],
    typeEngine: "text",
  },
  alltheinternet: {
    id: "card-allTheInternet",
    name: "AllTheInternet",
    key: "alltheinternet",
    urlToSite: "https://www.alltheinternet.com/",
    urls: [{ type: "text", link: "https://www.alltheinternet.com/?q=" }],
    located: "USA",
    svgName: "#allTheInternet-svg",
    keyColor: "#3657BA",
    logoSize: [100, 70],
    typeEngine: "text",
  },
  swisscows: {
    id: "card-swisscows",
    name: "Swisscows",
    key: "swisscows",
    urlToSite: "https://www.swisscows.com/",
    urls: [{ type: "text", link: "https://www.swisscows.com/web?query=" }],
    located: "Switzerland",
    svgName: "#swisscows-svg",
    keyColor: "#BF0000",
    logoSize: [100, 70],
    typeEngine: "text",
  },
  sears: {
    id: "card-sears",
    name: "Sears",
    key: "sears",
    urlToSite: "https://331221.xyz/",
    urls: [{ type: "text", link: "https://331221.xyz/search?q=" }],
    located: "Various",
    svgName: "#sears-svg",
    keyColor: "#25448B",
    logoSize: [100, 70],
    typeEngine: "text",
  },
  metager: {
    id: "card-metager",
    name: "MetaGer",
    key: "metager",
    urlToSite: "https://metager.org/",
    urls: [
      { type: "text", link: "https://metager.org/meta/meta.ger3?eingabe=" },
    ],
    located: "Germany",
    svgName: "#metager-svg",
    keyColor: "#F47215",
    logoSize: [100, 70],
    typeEngine: "text",
  },
  gibiru: {
    id: "card-gibiru",
    name: "Gibiru",
    key: "gibiru",
    urlToSite: "https://gibiru.com/",
    urls: [{ type: "text", link: "https://gibiru.com/results.html?q=" }],
    located: "USA",
    svgName: "#gibiru-svg",
    keyColor: "#FAB214",
    logoSize: [70, 70],
    typeEngine: "text",
  },
  googlescholar: {
    id: "card-googleScholar",
    name: "Google Scholar",
    key: "googlescholar",
    urlToSite: "https://scholar.google.com/",
    urls: [{ type: "text", link: "https://scholar.google.com/scholar?q=" }],
    located: "USA",
    svgName: "#googleScholar-svg",
    keyColor: "#76A7FA",
    logoSize: [70, 70],
    typeEngine: "text",
  },
  techcrunch: {
    id: "card-techcrunch",
    name: "TechCrunch",
    key: "techcrunch",
    urlToSite: "https://techcrunch.com/",
    urls: [{ type: "text", link: "https://search.techcrunch.com/search;?p=" }],
    located: "USA",
    svgName: "#techCrunch-svg",
    keyColor: "#0A9E01",
    logoSize: [70, 70],
    typeEngine: "text",
  },
  sogou: {
    id: "card-sogou",
    name: "Sogou",
    key: "sogou",
    urlToSite: "https://www.sogou.com/",
    urls: [{ type: "text", link: "https://www.sogou.com/web?query=" }],
    located: "China",
    svgName: "#sogou-svg",
    keyColor: "#FD6926",
    logoSize: [100, 70],
    typeEngine: "text",
  },
  mojeek: {
    id: "card-mojeek",
    name: "Mojeek",
    key: "mojeek",
    urlToSite: "https://www.mojeek.com/",
    urls: [{ type: "text", link: "https://www.mojeek.com/search?q=" }],
    located: "United Kingdom",
    svgName: "#mojeek-svg",
    keyColor: "#7AB93B",
    logoSize: [70, 70],
    typeEngine: "text",
  },
  excite: {
    id: "card-excite",
    name: "Excite",
    key: "excite",
    urlToSite: "https://www.excite.com/",
    urls: [{ type: "text", link: "https://search.excite.com/serp?q=" }],
    located: "United States",
    svgName: "#excite-svg",
    keyColor: "#CF4037",
    logoSize: [100, 70],
    typeEngine: "text",
  },
  hotbot: {
    id: "card-hotbot",
    name: "HotBot",
    key: "hotbot",
    urlToSite: "https://www.hotbot.com/",
    urls: [{ type: "text", link: "https://www.hotbot.com/web?q=" }],
    located: "United States",
    svgName: "#hotbot-svg",
    keyColor: "#FB3B4D",
    logoSize: [70, 70],
    typeEngine: "text",
  },
  yongzin: {
    id: "card-yongzin",
    name: "Yongzin",
    key: "yongzin",
    urlToSite: "https://www.yongzin.com/",
    urls: [
      {
        type: "text",
        link: "https://www.yongzin.com/page/search.do?user=&uid&word=",
      },
    ],
    located: "China",
    svgName: "#yongzin-svg",
    keyColor: "#009B59",
    logoSize: [100, 70],
    typeEngine: "text",
  },
  walla: {
    id: "card-walla",
    name: "Walla",
    key: "walla",
    urlToSite: "https://www.walla.co.il/",
    urls: [{ type: "text", link: "https://search.walla.co.il/?q=" }],
    located: "Israel",
    svgName: "#walla-svg",
    keyColor: "#00AEEF",
    logoSize: [100, 70],
    typeEngine: "text",
  },
  seznam: {
    id: "card-seznam",
    name: "Seznam",
    key: "seznam",
    urlToSite: "https://www.seznam.cz/",
    urls: [{ type: "text", link: "https://search.seznam.cz/?q=" }],
    located: "Czech Republic",
    svgName: "#seznam-svg",
    keyColor: "#E8000E",
    logoSize: [70, 70],
    typeEngine: "text",
  },
  rambler: {
    id: "card-rambler",
    name: "Rambler",
    key: "rambler",
    url: "https://www.rambler.ru/",
    urls: [{ type: "text", link: "https://nova.rambler.ru/search?&query=" }],
    located: "Russia",
    svgName: "#rambler-svg",
    keyColor: "#315EFB",
    logoSize: [100, 70],
    typeEngine: "text",
  },
};
